### ISSUE TITLE
Suggestion: Use R pkg structure

### ISSUE THREAD

**Issue by benmarwick** [archca/aca_data_collection#1]
These look very useful! Can I suggest that you organise them as an R package? There are many precedents for data-packages like this, even in archaeology. For example: [archdata](https://cran.rstudio.com/web/packages/archdata/index.html), [evoarchdata](https://github.com/benmarwick/evoarchdata), [gsloid](https://cran.r-project.org/web/packages/gsloid/index.html) and [binford](binford). 

This will standardise the documentation for each dataset, and make it easy for users to see how to cite the data. It will also make it easy for students to get the data onto their computer as a natural part of their R workflow.

Also, it's crucial that you have citation details for public data like these. This could just be in a README, but I think it's important to give credit to the original researchers by showing users how to cite the data producers. For more guidance on this, [please see this paper](http://faculty.washington.edu/bmarwick/PDFs/Marwick-and-Pilaar-Birch-2018-Data-Citation-AAP.pdf)

**Comment by MartinHinz** [comment]
Thank you for  the proposal, that is very useful. We currently build this repository up as a didactic exercise and plan to transfer it later into a proper R package.
