### ISSUE TITLE
cannot connect via SSH 

### ISSUE THREAD

**Issue by Poxl** [archca/aca_data_collection#2]
my account seems to not have writting access to the repository. Cloning works, but pushing results in denial.

Error message:
```
ERROR: Permission to archca/aca_data_collection.git denied to Poxl.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Lg Nico

**Comment by MartinHinz** [comment]
Thank you very much for reporting, I added you to the collaborators of the repository. read/write access should now be granted.
